# Generated by Django 3.1.6 on 2021-02-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(blank=True, max_length=255, null=True)),
                ('lavel', models.CharField(blank=True, choices=[('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SS1', 'SS1'), ('SS2', 'SS2'), ('SS3', 'SS3')], max_length=255, null=True)),
                ('term', models.CharField(blank=True, choices=[('FIRST', 'FIRST'), ('SECOND', 'SECOND'), ('THIRD', 'THIRD')], max_length=255, null=True)),
                ('week', models.CharField(blank=True, choices=[('WEEK1', 'WEEK1'), ('WEEK2', 'WEEK2'), ('WEEK3', 'WEEK3')], max_length=255, null=True)),
                ('salat', models.CharField(blank=True, choices=[('FAJR', 'FAJR'), ('ZUHR', 'ZUHR'), ('ASRI', 'ASRI'), ('MAGRIB', 'MAGRIB'), ('ISHA', 'ISHA')], max_length=255, null=True)),
                ('monday', models.IntegerField(blank=True, default=True, max_length=255, null=True)),
                ('tuesday', models.IntegerField(blank=True, default=True, max_length=255, null=True)),
                ('wednesday', models.IntegerField(blank=True, default=True, max_length=255, null=True)),
                ('thursday', models.IntegerField(blank=True, default=True, max_length=255, null=True)),
                ('friday', models.IntegerField(blank=True, default=True, max_length=255, null=True)),
                ('saturday', models.IntegerField(blank=True, default=True, max_length=255, null=True)),
                ('sunday', models.IntegerField(blank=True, default=True, max_length=255, null=True)),
            ],
        ),
    ]
