# Generated by Django 3.1.6 on 2021-02-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentreg', '0002_auto_20210228_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreg',
            name='friday',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='monday',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='saturday',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='sunday',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='thursday',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='tuesday',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='wednesday',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
