# Generated by Django 3.1.6 on 2021-03-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentreg', '0006_lightout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lightout',
            new_name='Dining',
        ),
    ]
