# Generated by Django 3.1.6 on 2021-03-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentreg', '0007_auto_20210305_1034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studentreg',
            new_name='Salat',
        ),
    ]
