# Generated by Django 3.1.6 on 2021-03-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentreg', '0009_lightout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightout',
            name='lightout',
            field=models.CharField(blank=True, choices=[('TIMELy', 'TIMELY'), ('OBEDIENT', 'OBEDIENT'), ('QUITNESSS', 'QUITNESS'), ('SWICH OF LIGHT', 'SWICH OF LIGHT')], max_length=255, null=True),
        ),
    ]
