# Generated by Django 3.1.6 on 2021-03-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentreg', '0015_auto_20210306_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salat',
            name='attitudes',
            field=models.CharField(blank=True, choices=[('ATTITUDE TO SALAT', 'ATTITUDE TO SALAT'), ('ATTITUDE TO DINING', 'ATTITUDE TO DINING'), ('ATTITUDE TO LIGHT OUT', 'ATTITUDE TO LIGHT OUT'), ('PERSONAL HYGIENE', 'PERSONAL HYGIENE'), ('COMPLIANCE TO PROPER DRESS CODE', 'COMPLIANCE TO PROPER DRESS CODE'), ('COMPLIANCE TO PREP CLASS', 'COMPLIANCE TO PREP CLASS'), ('GENERAL ATTITUDE ', 'GENERAL ATTITUDE ')], max_length=255, null=True),
        ),
    ]
