# Generated by Django 3.1.6 on 2021-03-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentreg', '0016_auto_20210306_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salat',
            name='attitudes',
            field=models.CharField(blank=True, choices=[('SALAT', 'SALAT'), ('DINING', 'DINING'), ('LIGHT OUT', 'LIGHT OUT'), ('HYGIENE', 'HYGIENE'), ('DRESS CODE', 'DRESS CODE'), ('PREP CLASS', 'PREP CLASS'), ('HOSTEL ADMIN/STUDENTS RELATIONSHIP', 'HOSTEL ADMIN/STUDENTS RELATIONSHIP')], max_length=255, null=True),
        ),
    ]
