# Generated by Django 3.1.6 on 2021-03-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentreg', '0019_auto_20210310_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salat',
            name='attitudes',
            field=models.CharField(blank=True, choices=[('SALAT', 'SALAT'), ('DINING', 'DINING'), ('LIGHT OUT', 'LIGHT OUT'), ('HYGIENE', 'HYGIENE'), ('DRESS CODE', 'DRESS CODE'), ('PREP CLASS', 'PREP CLASS'), ('ADMIN/STUDENTS', 'ADMIN/STUDENTS')], max_length=255, null=True),
        ),
    ]
