# Generated by Django 3.1.6 on 2021-03-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentreg', '0022_auto_20210310_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salat',
            name='attitudes',
            field=models.CharField(blank=True, choices=[('SALAT', 'SALAT'), ('DINING', 'DINING'), ('LIGHT OUT', 'LIGHT OUT'), ('HYGIENE', 'HYGIENE'), ('DRESS CODE', 'DRESS CODE'), ('PREP CLASS', 'PREP CLASS'), ('ADMIN/STUDENTS', 'ADMIN/STUDENTS ')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salat',
            name='friday',
            field=models.PositiveIntegerField(blank=True, default=14, null=True),
        ),
        migrations.AlterField(
            model_name='salat',
            name='monday',
            field=models.PositiveIntegerField(blank=True, default=14, null=True),
        ),
        migrations.AlterField(
            model_name='salat',
            name='saturday',
            field=models.PositiveIntegerField(blank=True, default=15, null=True),
        ),
        migrations.AlterField(
            model_name='salat',
            name='sunday',
            field=models.PositiveIntegerField(blank=True, default=15, null=True),
        ),
        migrations.AlterField(
            model_name='salat',
            name='thursday',
            field=models.PositiveIntegerField(blank=True, default=14, null=True),
        ),
        migrations.AlterField(
            model_name='salat',
            name='tuesday',
            field=models.PositiveIntegerField(blank=True, default=14, null=True),
        ),
        migrations.AlterField(
            model_name='salat',
            name='wednesday',
            field=models.PositiveIntegerField(blank=True, default=14, null=True),
        ),
    ]
