# Generated by Django 3.1.6 on 2021-06-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentreg', '0023_auto_20210310_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salat',
            name='attitudes',
            field=models.CharField(blank=True, choices=[('Salat', 'Salat'), ('Dining', 'Dining'), ('Light Out', 'Light Out'), ('Hygiene', 'Hygiene'), ('Dress Code', 'Dress Code'), ('Prep Class', 'Prep Class'), ('Admin/Students', 'Admin/Students ')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salat',
            name='term',
            field=models.CharField(blank=True, choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salat',
            name='week',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=255, null=True),
        ),
    ]
